version: '3'


services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    #command: bash -c "./app/entrypoint.prod.sh" 
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    hostname: app
    volumes:
      - ./app:/code
      - static:/code/
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - NEVERCACHE_KEY=bar
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=silver_journey
      - SQL_USER=silver_journey
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
  db:
    image: postgres
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=silver_journey
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=silver_journey
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - 8000:8000
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/code/:ro
    depends_on:
      - app

volumes:
  static:
  postgres_data:
