version: '3'

services:
  db:
    image: postgres
    hostname: db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./silver_journey/on-container-start.sh"
    hostname: app
    volumes:
      - ./app:/app
      - static:/srv
    expose:
      - 8000

    depends_on:
      - db
    #environment:
      #- DJANGO_SETTINGS_MODULE=silver_journey.local_settings
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - static:/srv:ro
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  static:
